
                (function() {
                    var nodeEnv = typeof require !== 'undefined' && typeof process !== 'undefined';
                    var __module = nodeEnv ? module : {exports:{}};
                    var __filename = 'preview-scripts/__qc_index__.js';
                    var __require = nodeEnv ? function (request) {
                        return cc.require(request);
                    } : function (request) {
                        return __quick_compile_project__.require(request, __filename);
                    };
                    function __define (exports, require, module) {
                        if (!nodeEnv) {__quick_compile_project__.registerModule(__filename, module);}
require('./assets/migration/use_reversed_rotateTo');
require('./assets/resources/SDK/SdkAdConfigData');
require('./assets/resources/SDK/module/BossKey/BossKey_SDK');
require('./assets/resources/SDK/module/BossKey/lieyou_BossKey_Prefab');
require('./assets/resources/SDK/module/common/lieyou_baseNode');
require('./assets/resources/SDK/module/common/lieyou_interface');
require('./assets/resources/SDK/module/lieyou_InstallShortcutPrefab');
require('./assets/resources/SDK/module/praise/lieyou_praiseDialog');
require('./assets/resources/SDK/module/qGameNativeAd/lieyou_nativeAdPrefab');
require('./assets/resources/SDK/module/qGameNativeAd/lieyou_nativeLoad');
require('./assets/resources/SDK/module/qGameNativeAd/lieyou_oppoNativeAdSdk');
require('./assets/resources/SDK/module/qGameNativeAd/nativePlayIconADSdk');
require('./assets/resources/SDK/module/qgameMoreGame/lieyou_qGameMoreGamePrefab');
require('./assets/resources/SDK/module/qgameMoreGame/lieyou_qGameMoreGame_showMore');
require('./assets/resources/SDK/module/qgameMoreGame/lieyou_qGamemoreGame_icon');
require('./assets/resources/SDK/module/qgameMoreGame/lieyou_qGamemoreGame_mid');
require('./assets/resources/SDK/module/qgameMoreGame/lieyou_qGamemoreGame_more');
require('./assets/resources/SDK/module/qqAppBox/lieyou_qqAppBox');
require('./assets/resources/SDK/module/redPack/lieyou_redPackDialog');
require('./assets/resources/SDK/module/tt_luPing/lieyou_tt_Prefab');
require('./assets/resources/SDK/module/tt_luPing/lieyou_tt_luPing');
require('./assets/resources/SDK/scripts/BaiDuManager');
require('./assets/resources/SDK/scripts/BaseManager');
require('./assets/resources/SDK/scripts/FaceBookManager');
require('./assets/resources/SDK/scripts/HuaweiManager');
require('./assets/resources/SDK/scripts/JinRiTouTiaoManager');
require('./assets/resources/SDK/scripts/MagicManagerH5');
require('./assets/resources/SDK/scripts/NativeManager');
require('./assets/resources/SDK/scripts/OppoH5Manager');
require('./assets/resources/SDK/scripts/OppoManager');
require('./assets/resources/SDK/scripts/QQManager');
require('./assets/resources/SDK/scripts/QuTouTiaoManagerH5');
require('./assets/resources/SDK/scripts/SdkData');
require('./assets/resources/SDK/scripts/SdkManager');
require('./assets/resources/SDK/scripts/VivoManager');
require('./assets/resources/SDK/scripts/WxManager');
require('./assets/resources/SDK/scripts/XiaoMiManager');
require('./assets/resources/SDK/scripts/XiaoMiManagerH5');
require('./assets/resources/SDK/scripts/lieyou_webManager');
require('./assets/script/Framework/AudioMgr');
require('./assets/script/Framework/CocosZ');
require('./assets/script/Framework/Constant');
require('./assets/script/Framework/DataMgr');
require('./assets/script/Framework/GameBgCtr');
require('./assets/script/Framework/GameCtr');
require('./assets/script/Framework/GameMgr');
require('./assets/script/Framework/Msg');
require('./assets/script/Framework/NormalModelCtr');
require('./assets/script/Framework/QEasing');
require('./assets/script/Framework/QMoveAction');
require('./assets/script/Framework/QRotation');
require('./assets/script/Framework/QScaleAction');
require('./assets/script/Framework/ResMgr');
require('./assets/script/Framework/SceneMgr');
require('./assets/script/Framework/UIMgr');
require('./assets/script/Game/NewScript');
require('./assets/script/Game/baffle');
require('./assets/script/Game/balloon');
require('./assets/script/Game/balloon2');
require('./assets/script/Game/bat');
require('./assets/script/Game/boom');
require('./assets/script/Game/cactus');
require('./assets/script/Game/coin');
require('./assets/script/Game/controlCenter');
require('./assets/script/Game/fan');
require('./assets/script/Game/gameBg');
require('./assets/script/Game/handTips');
require('./assets/script/Game/labelTips');
require('./assets/script/Game/laser');
require('./assets/script/Game/laserEffect');
require('./assets/script/Game/limit3');
require('./assets/script/Game/listen');
require('./assets/script/Game/mapMask');
require('./assets/script/Game/moveFloor');
require('./assets/script/Game/otherCamera');
require('./assets/script/Game/propBigFan');
require('./assets/script/Game/propCacTus');
require('./assets/script/Game/propChainRocket');
require('./assets/script/Game/propCloud');
require('./assets/script/Game/propHoneybee');
require('./assets/script/Game/propMoveFloo10');
require('./assets/script/Game/propMoveFloor');
require('./assets/script/Game/propMoveFloor11');
require('./assets/script/Game/propMoveFloor12');
require('./assets/script/Game/propMoveFloor13');
require('./assets/script/Game/propMoveFloor14');
require('./assets/script/Game/propMoveFloor15');
require('./assets/script/Game/propMoveFloor16');
require('./assets/script/Game/propMoveFloor17');
require('./assets/script/Game/propMoveFloor18');
require('./assets/script/Game/propMoveFloor2');
require('./assets/script/Game/propMoveFloor21');
require('./assets/script/Game/propMoveFloor3');
require('./assets/script/Game/propMoveFloor9');
require('./assets/script/Game/propRocket');
require('./assets/script/Game/propRocket2');
require('./assets/script/Game/propRotateFloor');
require('./assets/script/Game/propWooldenBox');
require('./assets/script/Game/rain');
require('./assets/script/Game/rewardRocket');
require('./assets/script/Game/rocketEffect');
require('./assets/script/Game/role');
require('./assets/script/Game/rope');
require('./assets/script/Game/sandEffect');
require('./assets/script/Game/stone');
require('./assets/script/Game/tes');
require('./assets/script/Game/test');
require('./assets/script/Game/thorn');
require('./assets/script/Ui/LevelItem');
require('./assets/script/Ui/LevelPanel');
require('./assets/script/Ui/Lottery');
require('./assets/script/Ui/PausePanel');
require('./assets/script/Ui/UIPage');
require('./assets/script/Ui/UiBeforeSucceed');
require('./assets/script/Ui/UiFailed');
require('./assets/script/Ui/UiGame');
require('./assets/script/Ui/UiHome');
require('./assets/script/Ui/UiLoad');
require('./assets/script/Ui/UiLottery');
require('./assets/script/Ui/UiResurrection');
require('./assets/script/Ui/UiSet');
require('./assets/script/Ui/UiShop');
require('./assets/script/Ui/UiSign');
require('./assets/script/Ui/UiSucceed');
require('./assets/script/Ui/propItem');
require('./assets/script/Ui/rewardLevel');
require('./assets/script/Ui/rewardLevel2');
require('./assets/script/Ui/shopItem');
require('./assets/script/utils/ald-game-conf');
require('./assets/script/utils/ald-game');
require('./assets/script/ysqszc/bat2');
require('./assets/script/ysqszc/cloud');
require('./assets/script/ysqszc/game2');
require('./assets/script/ysqszc/launchPoint');
require('./assets/script/ysqszc/levelNum');
require('./assets/script/ysqszc/nimiCactus');
require('./assets/script/ysqszc/propCactus');
require('./assets/script/ysqszc/sBoard');
require('./assets/script/ysqszc/stone2');
require('./assets/script/ysqszc/theBall');
require('./assets/script/ysqszc/tt');

                    }
                    if (nodeEnv) {
                        __define(__module.exports, __require, __module);
                    }
                    else {
                        __quick_compile_project__.registerModuleFunc(__filename, function () {
                            __define(__module.exports, __require, __module);
                        });
                    }
                })();